//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalBrazucas
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticias
    {
        public noticias()
        {
            this.comentarios = new HashSet<comentarios>();
        }
    
        public int idNoticia { get; set; }
        public int idUsuario { get; set; }
        public string tituloNoticia { get; set; }
        public string conteudoNoticia { get; set; }
        public string fonteNoticia { get; set; }
        public string url_imagem { get; set; }
    
        public virtual ICollection<comentarios> comentarios { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
