//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalBrazucas
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public usuarios()
        {
            this.anuncios = new HashSet<anuncios>();
            this.noticias = new HashSet<noticias>();
            this.palpites = new HashSet<palpites>();
        }
    
        public int idUsuario { get; set; }
        public string nomeUsuario { get; set; }
        public string emailUsuario { get; set; }
        public string senhaUsuario { get; set; }
        public int idTipoUsuario { get; set; }
    
        public virtual ICollection<anuncios> anuncios { get; set; }
        public virtual ICollection<noticias> noticias { get; set; }
        public virtual ICollection<palpites> palpites { get; set; }
        public virtual tiposusuario tiposusuario { get; set; }
    }
}
