//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalBrazucas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdportalEntities : DbContext
    {
        public bdportalEntities()
            : base("name=bdportalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<anuncios> anuncios { get; set; }
        public DbSet<boloes> boloes { get; set; }
        public DbSet<cidades> cidades { get; set; }
        public DbSet<comentarios> comentarios { get; set; }
        public DbSet<estadios> estadios { get; set; }
        public DbSet<jogos> jogos { get; set; }
        public DbSet<noticias> noticias { get; set; }
        public DbSet<palpites> palpites { get; set; }
        public DbSet<selecoes> selecoes { get; set; }
        public DbSet<tabela> tabela { get; set; }
        public DbSet<tiposusuario> tiposusuario { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
