//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalBrazucas
{
    using System;
    using System.Collections.Generic;
    
    public partial class selecoes
    {
        public selecoes()
        {
            this.boloes = new HashSet<boloes>();
            this.boloes1 = new HashSet<boloes>();
            this.jogos = new HashSet<jogos>();
            this.jogos1 = new HashSet<jogos>();
            this.tabela = new HashSet<tabela>();
        }
    
        public int idSelecao { get; set; }
        public string nomeSelecao { get; set; }
    
        public virtual ICollection<boloes> boloes { get; set; }
        public virtual ICollection<boloes> boloes1 { get; set; }
        public virtual ICollection<jogos> jogos { get; set; }
        public virtual ICollection<jogos> jogos1 { get; set; }
        public virtual ICollection<tabela> tabela { get; set; }
    }
}
