//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalBrazucas
{
    using System;
    using System.Collections.Generic;
    
    public partial class cidades
    {
        public cidades()
        {
            this.estadios = new HashSet<estadios>();
        }
    
        public int idCidade { get; set; }
        public string nomeCidade { get; set; }
        public string siglaCidade { get; set; }
        public Nullable<double> areaCidade { get; set; }
        public Nullable<int> populacaoCidade { get; set; }
        public string climaCidade { get; set; }
        public string siteCidade { get; set; }
    
        public virtual ICollection<estadios> estadios { get; set; }
    }
}
