//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalBrazucas
{
    using System;
    using System.Collections.Generic;
    
    public partial class estadios
    {
        public estadios()
        {
            this.jogos = new HashSet<jogos>();
        }
    
        public int idEstadio { get; set; }
        public string nomeEstadio { get; set; }
        public string logradouro { get; set; }
        public int idCidade { get; set; }
    
        public virtual cidades cidades { get; set; }
        public virtual ICollection<jogos> jogos { get; set; }
    }
}
