//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalBrazucas
{
    using System;
    using System.Collections.Generic;
    
    public partial class boloes
    {
        public boloes()
        {
            this.palpites = new HashSet<palpites>();
        }
    
        public int idBolao { get; set; }
        public System.DateTime dataInicioBolao { get; set; }
        public System.DateTime dataFimBolao { get; set; }
        public System.TimeSpan horaInicioInicio { get; set; }
        public System.TimeSpan horaFimBolao { get; set; }
        public Nullable<int> palpiteVencedorBolao { get; set; }
        public int equipeA { get; set; }
        public int equipeB { get; set; }
    
        public virtual ICollection<palpites> palpites { get; set; }
        public virtual selecoes selecoes { get; set; }
        public virtual selecoes selecoes1 { get; set; }
    }
}
