//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalBrazucas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabela
    {
        public int idTabela { get; set; }
        public int selecaoTabela { get; set; }
        public int vitoriasTabela { get; set; }
        public int derrotasTabela { get; set; }
        public int empatesTabela { get; set; }
        public int golsMarcados { get; set; }
        public int golsSofridos { get; set; }
    
        public virtual selecoes selecoes { get; set; }
    }
}
